### ISSUE TITLE
Stack level too deep error in String::concat

### ISSUE THREAD

**Issue by lyi2012** [kristianmandrup/sugar-high#17]
I am using sugar-high (0.4.6.4) with activesupport (3.2.11) and running into "Stack level too deep" error.

![image](https://f.cloud.github.com/assets/1736156/1287314/e319f95c-2ff2-11e3-8cd6-d470e552fe79.png)

**Comment by kristianmandrup** [comment]
Try calling the method something else and see what happens. 

Fx concats

It might also conflict with another concat method in String defined by another lib?
Either use the new refinements feature of Ruby 2.0+ or perhaps only add the concat method if not already present in String. There are other methods in sugar-high which uses the latter approach.
Then add sugar-high dependency (or roles_generic whatever) as a late gem dependency, so that other gems have the chance to add in their version of concat to string.

Run the gem specs and see if you still get the same error.

Simply calls for more debugging. I have not the time now. I'm not using Ruby these days either…

Cheers.

Kristian

**Comment by stanislaw** [comment]
Hey @lyi2012, why are you trying to use such an old version of the gem (0.4.6.4)?

Current gem version is http://rubygems.org/gems/sugar-high is 0.7.3.

I recognize the problem you are talking about but it has been fixed a long time ago by something like [this](https://github.com/kristianmandrup/sugar-high/commit/c07b3ba25ea0cb5b1fe154e3381e216b65853693). Then later this method was cut off from sugar-high completely because I guess it appeared in the recent versions of Ruby by default.

**Comment by kristianmandrup** [comment]
If you are using gem dependent on all version of sugar-high, update the gem to have dependency on latest version, then go from there. Thanks Stan ;)
